#pragma once

#define k_minimum_physics_model_shape_reference_count 128
#define k_environement_body_user_data 3401362352

bool __cdecl havok_can_allocate_space_for_instance_of_object_definition(datum tag_index);
