#pragma once

/* enums */

enum e_achievement_type
{
	_achievement_type_cairo_station= 0,
	_achievement_type_outskirts,
	_achievement_type_metropolis,
	_achievement_type_the_arbiter,
	_achievement_type_oracle,
	_achievement_type_delta_halo,
	_achievement_type_regret,
	_achievement_type_sacred_icon,
	_achievement_type_quarantine_zone,
	_achievement_type_gravemind,
	_achievement_type_uprising,
	_achievement_type_high_charity,
	_achievement_type_the_great_journey,
	_achievement_type_warrior,
	_achievement_type_hero,
	_achievement_type_legend,
	_achievement_type_king_of_the_scarab,
	_achievement_type_silent_but_deadly,
	_achievement_type_demon,
	_achievement_type_go_ape_shit,
	_achievement_type_stick_it,
	_achievement_type_counterpoint,
	_achievement_type_carjacking,
	_achievement_type_violent_cartographer,
	_achievement_type_rainman,
	_achievement_type_double_kill,
	_achievement_type_triple_kill,
	_achievement_type_killtacular,
	_achievement_type_killing_spree,
	_achievement_type_running_riot,
	_achievement_type_sniper_kill,
	_achievement_type_roadkill,
	_achievement_type_bonecracker,
	_achievement_type_assassin,
	_achievement_type_skewer_stopper,
	_achievement_type_vigilante,
	_achievement_type_air_traffic_controller,
	_achievement_type_decorated_soldier,
	_achievement_type_ninja,
	_achievement_type_flaming_ninja,
	_achievement_type_hired_gun,
	k_achievement_type_count
};
