#pragma once
#include "game/game_allegiance.h"
#include "input/controllers.h"

/* enums */

enum e_user_interface_controller_handicap : int8
{
	_user_interface_controller_handicap_none = 0,
	_user_interface_controller_handicap_minor,
	_user_interface_controller_handicap_moderate,
	_user_interface_controller_handicap_severe,

	k_user_interface_controller_handicap_count
};

enum e_user_interface_automation_mode : uint16
{
	_user_interface_automation_mode_none = 0x0,
	_user_interface_automation_mode_campaign_single_player,
	_user_interface_automation_mode_splitscreen_multiplayer,
	_user_interface_automation_mode_system_link_auto,
	_user_interface_automation_mode_system_link_auto_host,
	_user_interface_automation_mode_system_link_auto_join,
	_user_interface_automation_mode_system_link_manual,
	_user_interface_automation_mode_xbox_live_auto,
	_user_interface_automation_mode_xbox_live_auto_host,
	_user_interface_automation_mode_xbox_live_auto_join,
	_user_interface_automation_mode_xbox_live_manual,
	_user_interface_automation_mode_matchmaking,
	k_user_interface_automation_modes_count,
};

enum e_controller_state_flags
{
	_controller_state_is_attached_bit = 0,
	_controller_state_bit1,//drive_test1
	_controller_state_bit2,//drive_test2
	_controller_state_has_valid_profile_bit,
	_controller_state_has_xbox_live_bit,
	_controller_state_save_in_progress_bit,
	_controller_state_bit6,

	//TODO : figure out all flags
	k_controller_state_flags_count,
};

/* prototypes */

void user_interface_controller_apply_patches(void);

void __cdecl user_interface_controller_initialize(void);
void __cdecl user_interface_controller_update(void);
bool __cdecl user_interface_controller_is_player_profile_valid(e_controller_index controller_index);
e_controller_index __cdecl user_interface_controller_get_next_valid_index(e_controller_index controller_index);
uint32 __cdecl user_interface_controller_get_user_index(e_controller_index controller_index);
void __cdecl user_interface_controller_set_user_index(e_controller_index controller_index, uint32 user_index);
e_controller_index __cdecl user_interface_controller_get_controller_for_user(uint32 user_index);
e_controller_index __cdecl user_interface_controller_get_first_valid_controller();
e_game_team __cdecl user_interface_controller_get_user_active_team(e_controller_index controller_index);
void __cdecl user_interface_controller_set_desired_team_index(e_controller_index controller_index, e_game_team team);
bool __cdecl user_interface_controller_get_rumble_enabled(e_controller_index controller_index);
bool __cdecl user_interface_controller_get_autolevel_enabled(e_controller_index controller_index);
e_user_interface_controller_handicap __cdecl user_interface_controller_get_user_handicap_level(e_controller_index controller_index);
void __cdecl user_interface_controller_set_user_handicap_level(e_controller_index controller_index, e_user_interface_controller_handicap handicap);
void __cdecl user_interface_controller_set_griefer(e_controller_index controller_index, bool griefing);
wchar_t* __cdecl user_interface_controller_get_player_profile_name(e_controller_index controller_index);

uint32 __cdecl user_interface_controller_get_signed_in_controller_count(void);
uint16 __cdecl user_interface_controller_get_signed_in_controllers_mask(void);
uint32 __cdecl user_interface_controller_get_last_level_played(e_controller_index controller_index);
uint32 __cdecl user_interface_controller_get_highest_campaign_level_in_signed_in_controllers();
bool __cdecl user_interface_controller_sign_in(e_controller_index controller_index, struct s_saved_game_player_profile* profile, uint32 enumerated_file_index);
void __cdecl user_interface_controller_sign_out(e_controller_index controller_index);
void __cdecl user_interface_controller_sign_out_all_controllers();
void __cdecl user_interface_controller_get_profile_data(e_controller_index controller_index, struct s_saved_game_player_profile* profile, uint32* profile_index);
void __cdecl user_interface_controller_get_user_properties(e_controller_index controller_index, struct s_player_identifier* controller_user_identifier, struct s_player_configuration* properties);
void __cdecl user_interface_controller_event_submit(struct s_event_record* event);

void __cdecl user_interface_controller_update_network_properties(e_controller_index controller_index);
void __cdecl user_interface_controller_pick_profile_dialog(e_controller_index controller_index, bool online_user);
bool __cdecl user_interface_controller_pick_profile_offline(e_controller_index controller_index);
bool __cdecl user_interface_controller_has_gamepad(e_controller_index controller_index);
bool __cdecl user_interface_controller_has_gamepad_just_left(e_controller_index controller_index);
bool __cdecl user_interface_controller_is_guest(e_controller_index controller_index);
uint32 __cdecl user_interface_controller_get_guest_controllers_count_for_master(e_controller_index master_controller_index);
bool __cdecl user_interface_controller_has_xbox_live(e_controller_index controller_index);
void __cdecl user_interface_controller_xbox_live_account_set_signed_in(e_controller_index controller_index, bool active);
void __cdecl user_interface_controller_update_player_name(e_controller_index controller_index);

