name: Build Cartographer

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-win:
    env:
      SOLUTION_FILE_PATH: .
      PLATFORM: x86
    strategy:
      matrix:
        # Use this when we fix llvm builds
        #BUILD_CONFIGURATION: [debug_msvc, debug_llvm, release_msvc, release_llvm]
        BUILD_CONFIGURATION: [debug_msvc, release_msvc]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4.1.6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{env.PLATFORM}} ${{matrix.SOLUTION_FILE_PATH}}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.5.0
      with:
        name: xlive ${{matrix.BUILD_CONFIGURATION}}
        path: |
            ./Halo2/xlive.dll
            ./Halo2/xlive.map
            ./xlive/${{matrix.BUILD_CONFIGURATION}}/xlive.pdb